rtl.module("Web",["System","Types","JS","weborworker"],function () {
  "use strict";
  var $mod = this;
  $mod.$rtti.$ExtClass("TJSHTMLElement");
  $mod.$rtti.$ExtClass("TJSWindow");
  $mod.$rtti.$ExtClass("TJSDOMTokenList");
  $mod.$rtti.$ExtClass("TJSXPathResult");
  $mod.$rtti.$ExtClass("TJSNodeList");
  $mod.$rtti.$ExtClass("TJSDocument");
  $mod.$rtti.$ExtClass("TJSElement");
  $mod.$rtti.$ExtClass("TJSCSSStyleSheet");
  $mod.$rtti.$ExtClass("TJSNodeFilter");
  $mod.$rtti.$ExtClass("TJSShadowRoot");
  $mod.$rtti.$ExtClass("TJSAnimation");
  $mod.$rtti.$ExtClass("TJSAnimationTimeline");
  $mod.$rtti.$ExtClass("TJSMouseEvent");
  $mod.$rtti.$ExtClass("TJSWheelEvent");
  $mod.$rtti.$ExtClass("TJSKeyboardEvent");
  $mod.$rtti.$ExtClass("TJSPointerEvent");
  $mod.$rtti.$ExtClass("TJSUIEvent");
  $mod.$rtti.$ExtClass("TJSTouchEvent");
  $mod.$rtti.$ExtClass("TJSShowOpenFilePickerOptions");
  $mod.$rtti.$ExtClass("TJSShowSaveFilePickerOptions");
  $mod.$rtti.$ExtClass("TJSHTMLResizeObserver");
  $mod.$rtti.$RefToProcVar("TJSEventHandler",{procsig: rtl.newTIProcSig([["Event",pas.weborworker.$rtti["TJSEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSRawEventHandler",{procsig: rtl.newTIProcSig([["Event",pas.weborworker.$rtti["TJSEvent"]]],8)});
  $mod.$rtti.$ExtClass("TJSNode",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "Node"});
  $mod.$rtti.$RefToProcVar("TJSNodeListCallBack",{procsig: rtl.newTIProcSig([["currentValue",$mod.$rtti["TJSNode"]],["currentIndex",rtl.nativeint],["list",$mod.$rtti["TJSNodeList"]]])});
  $mod.$rtti.$ExtClass("TJSNodeList",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "NodeList"});
  $mod.$rtti.$ExtClass("TJSAttr",{ancestor: $mod.$rtti["TJSNode"], jsclass: "Attr"});
  $mod.$rtti.$ExtClass("TJSNamedNodeMap",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "NamedNodeMap"});
  $mod.$rtti.$ExtClass("TJSHTMLCollection",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "HTMLCollection"});
  $mod.$rtti.$ProcVar("TDOMTokenlistCallBack",{procsig: rtl.newTIProcSig([["Current",rtl.jsvalue],["currentIndex",rtl.nativeint],["list",$mod.$rtti["TJSDOMTokenList"]]])});
  $mod.$rtti.$ExtClass("TJSDOMTokenList",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "DOMTokenList"});
  $mod.$rtti.$ExtClass("TJSDOMRect",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "DOMRect"});
  $mod.$rtti.$ExtClass("TJSDOMRectReadOnly",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "DOMRect"});
  rtl.recNewT($mod,"TJSClientRect",function () {
    this.left = 0.0;
    this.top = 0.0;
    this.right = 0.0;
    this.bottom = 0.0;
    this.$eq = function (b) {
      return (this.left === b.left) && (this.top === b.top) && (this.right === b.right) && (this.bottom === b.bottom);
    };
    this.$assign = function (s) {
      this.left = s.left;
      this.top = s.top;
      this.right = s.right;
      this.bottom = s.bottom;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSClientRect",{});
    $r.addField("left",rtl.double);
    $r.addField("top",rtl.double);
    $r.addField("right",rtl.double);
    $r.addField("bottom",rtl.double);
  });
  $mod.$rtti.$ExtClass("TJSScrollOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSCheckVisibilityOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSAttachShadowOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSAnimateOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSElement",{ancestor: $mod.$rtti["TJSNode"], jsclass: "Element"});
  rtl.recNewT($mod,"TJSElementCreationOptions",function () {
    this.named = "";
    this.$eq = function (b) {
      return this.named === b.named;
    };
    this.$assign = function (s) {
      this.named = s.named;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSElementCreationOptions",{});
    $r.addField("named",rtl.string);
  });
  $mod.$rtti.$ExtClass("TJSDocumentType",{ancestor: $mod.$rtti["TJSNode"], jsclass: "DocumentType"});
  $mod.$rtti.$ExtClass("TJSDOMImplementation",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "DocumentImplementation"});
  $mod.$rtti.$ExtClass("TJSLocation",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Location"});
  $mod.$rtti.$ExtClass("TJSCSSStyleDeclaration");
  $mod.$rtti.$ExtClass("TJSStyleSheet",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "StyleSheet"});
  $mod.$rtti.$ExtClass("TJSCSSRule",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "CSSRule"});
  $mod.$rtti.$ExtClass("TJSCSSStyleRule",{ancestor: $mod.$rtti["TJSCSSRule"], jsclass: "CSSStyleRule"});
  $mod.$rtti.$ExtClass("TJSCSSRuleList",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "CSSRuleList"});
  $mod.$rtti.$ExtClass("TJSCSSStyleSheet",{ancestor: $mod.$rtti["TJSStyleSheet"], jsclass: "CSSStyleSheet"});
  $mod.$rtti.$ExtClass("TJSStyleSheetList",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "StyleSheetList"});
  $mod.$rtti.$ExtClass("TJSDocumentFragment",{ancestor: $mod.$rtti["TJSNode"], jsclass: "DocumentFragment"});
  this.TJSShadowRootMode = {"0": "open", open: 0, "1": "closed", closed: 1};
  this.TJSSlotAssignmentMode = {"0": "manual", manual: 0, "1": "named", named: 1};
  $mod.$rtti.$Enum("TJSSlotAssignmentMode",{minvalue: 0, maxvalue: 1, ordtype: 1, enumtype: this.TJSSlotAssignmentMode});
  $mod.$rtti.$ExtClass("TJSShadowRoot",{ancestor: $mod.$rtti["TJSDocumentFragment"], jsclass: "ShadowRoot"});
  rtl.createHelper($mod,"TJSEventHelper",null,function () {
    this.GetCurrentTargetElement = function () {
      var Result = null;
      Result = this.currentTarget;
      return Result;
    };
    this.GetCurrentTargetHTMLElement = function () {
      var Result = null;
      Result = this.currentTarget;
      return Result;
    };
    this.GetTargetElement = function () {
      var Result = null;
      Result = this.target;
      return Result;
    };
    this.GetTargetHTMLElement = function () {
      var Result = null;
      Result = this.target;
      return Result;
    };
  });
  $mod.$rtti.$ExtClass("TJSXPathExpression",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "XPathExpression"});
  $mod.$rtti.$ExtClass("TJSXPathNSResolver",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "XPathNSResolver"});
  $mod.$rtti.$ExtClass("TJSCharacterData",{ancestor: $mod.$rtti["TJSNode"], jsclass: "CharacterData"});
  $mod.$rtti.$ExtClass("TJSProcessingInstruction",{ancestor: $mod.$rtti["TJSCharacterData"], jsclass: "ProcessingInstruction"});
  $mod.$rtti.$ExtClass("TJSRange",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Range"});
  $mod.$rtti.$ExtClass("TJSTreeWalker",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "TreeWalker"});
  $mod.$rtti.$ExtClass("TJSNodeFilter",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "NodeFilter"});
  $mod.$rtti.$ExtClass("TJSXPathResult",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "XPathResult"});
  $mod.$rtti.$ExtClass("TJSSelection",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Selection"});
  $mod.$rtti.$ProcVar("TJSNameSpaceMapperCallback",{procsig: rtl.newTIProcSig([["aNameSpace",rtl.string]],rtl.string)});
  $mod.$rtti.$ExtClass("TJSHTMLFile");
  $mod.$rtti.$ExtClass("TJSHTMLFileList");
  $mod.$rtti.$RefToProcVar("TJSDataTransferItemCallBack",{procsig: rtl.newTIProcSig([["aData",rtl.string]],8)});
  $mod.$rtti.$ExtClass("TJSDataTransferItem",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "DataTransferItem"});
  $mod.$rtti.$ExtClass("TJSDataTransferItemList",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "DataTransferItemList"});
  $mod.$rtti.$ExtClass("TJSDataTransfer",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "DataTransfer"});
  $mod.$rtti.$ExtClass("TJSDragEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "DragEvent"});
  $mod.$rtti.$RefToProcVar("TJSDragDropEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSDragEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("THTMLClickEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSMouseEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$ExtClass("TJSClipBoardEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "ClipboardEvent"});
  $mod.$rtti.$ExtClass("TJSFocusEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "FocusEvent"});
  $mod.$rtti.$ExtClass("TJSAnimationEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "AnimationEvent"});
  $mod.$rtti.$ExtClass("TJSLoadEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "LoadEvent"});
  $mod.$rtti.$ExtClass("TJSErrorEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "ErrorEvent"});
  $mod.$rtti.$ExtClass("TJSPageTransitionEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "PageTransitionEvent"});
  $mod.$rtti.$ExtClass("TJSHashChangeEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "HashChangeEvent"});
  $mod.$rtti.$ExtClass("TJSPopStateEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "PopStateEvent"});
  $mod.$rtti.$ExtClass("TJSStorageEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "StorageEvent"});
  $mod.$rtti.$ExtClass("TJSProgressEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "ProgressEvent"});
  $mod.$rtti.$ExtClass("TJSCloseEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "CloseEvent"});
  $mod.$rtti.$RefToProcVar("TJSPageTransitionEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSPageTransitionEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSHashChangeEventhandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSHashChangeEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSMouseWheelEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSWheelEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSMouseEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSMouseEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("THTMLAnimationEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSAnimationEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSErrorEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSErrorEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSFocusEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSFocusEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSKeyEventhandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSKeyboardEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSLoadEventhandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSLoadEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSPointerEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSPointerEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSUIEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSUIEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSPopStateEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSPopStateEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSStorageEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSStorageEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSProgressEventhandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSProgressEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$RefToProcVar("TJSTouchEventHandler",{procsig: rtl.newTIProcSig([["aEvent",$mod.$rtti["TJSTouchEvent"]]],rtl.boolean,8)});
  $mod.$rtti.$ExtClass("TJSDocument",{ancestor: $mod.$rtti["TJSNode"], jsclass: "Document"});
  $mod.$rtti.$ExtClass("TJSHistory",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "History"});
  $mod.$rtti.$ExtClass("TJSStorage",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "Storage"});
  $mod.$rtti.$ExtClass("TJSVisibleItem",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "IVisible"});
  $mod.$rtti.$ExtClass("TJSLocationBar",{ancestor: $mod.$rtti["TJSVisibleItem"], jsclass: "LocationBar"});
  $mod.$rtti.$ExtClass("TJSMenuBar",{ancestor: $mod.$rtti["TJSVisibleItem"], jsclass: "MenuBar"});
  $mod.$rtti.$ExtClass("TJSToolBar",{ancestor: $mod.$rtti["TJSVisibleItem"], jsclass: "ToolBar"});
  $mod.$rtti.$ExtClass("TJSPersonalBar",{ancestor: $mod.$rtti["TJSVisibleItem"], jsclass: "PersonalBar"});
  $mod.$rtti.$ExtClass("TJSScrollBars",{ancestor: $mod.$rtti["TJSVisibleItem"], jsclass: "ScrollBars"});
  rtl.recNewT($mod,"TJSPositionError",function () {
    this.code = 0;
    this.message = "";
    this.$eq = function (b) {
      return (this.code === b.code) && (this.message === b.message);
    };
    this.$assign = function (s) {
      this.code = s.code;
      this.message = s.message;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSPositionError",{});
    $r.addField("code",rtl.longint);
    $r.addField("message",rtl.string);
  });
  rtl.recNewT($mod,"TJSPositionOptions",function () {
    this.enableHighAccuracy = false;
    this.timeout = 0;
    this.maximumAge = 0;
    this.$eq = function (b) {
      return (this.enableHighAccuracy === b.enableHighAccuracy) && (this.timeout === b.timeout) && (this.maximumAge === b.maximumAge);
    };
    this.$assign = function (s) {
      this.enableHighAccuracy = s.enableHighAccuracy;
      this.timeout = s.timeout;
      this.maximumAge = s.maximumAge;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSPositionOptions",{});
    $r.addField("enableHighAccuracy",rtl.boolean);
    $r.addField("timeout",rtl.longint);
    $r.addField("maximumAge",rtl.longint);
  });
  rtl.recNewT($mod,"TJSCoordinates",function () {
    this.latitude = 0.0;
    this.longitude = 0.0;
    this.altitude = 0.0;
    this.accuracy = 0.0;
    this.altitudeAccuracy = 0.0;
    this.heading = 0.0;
    this.speed = 0.0;
    this.$eq = function (b) {
      return (this.latitude === b.latitude) && (this.longitude === b.longitude) && (this.altitude === b.altitude) && (this.accuracy === b.accuracy) && (this.altitudeAccuracy === b.altitudeAccuracy) && (this.heading === b.heading) && (this.speed === b.speed);
    };
    this.$assign = function (s) {
      this.latitude = s.latitude;
      this.longitude = s.longitude;
      this.altitude = s.altitude;
      this.accuracy = s.accuracy;
      this.altitudeAccuracy = s.altitudeAccuracy;
      this.heading = s.heading;
      this.speed = s.speed;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSCoordinates",{});
    $r.addField("latitude",rtl.double);
    $r.addField("longitude",rtl.double);
    $r.addField("altitude",rtl.double);
    $r.addField("accuracy",rtl.double);
    $r.addField("altitudeAccuracy",rtl.double);
    $r.addField("heading",rtl.double);
    $r.addField("speed",rtl.double);
  });
  rtl.recNewT($mod,"TJSPosition",function () {
    this.timestamp = "";
    this.$new = function () {
      var r = Object.create(this);
      r.coords = $mod.TJSCoordinates.$new();
      return r;
    };
    this.$eq = function (b) {
      return this.coords.$eq(b.coords) && (this.timestamp === b.timestamp);
    };
    this.$assign = function (s) {
      this.coords.$assign(s.coords);
      this.timestamp = s.timestamp;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSPosition",{});
    $r.addField("coords",$mod.$rtti["TJSCoordinates"]);
    $r.addField("timestamp",rtl.string);
  });
  $mod.$rtti.$ProcVar("TJSGeoLocationCallback",{procsig: rtl.newTIProcSig([["aPosition",$mod.$rtti["TJSPosition"]]])});
  $mod.$rtti.$MethodVar("TJSGeoLocationEvent",{procsig: rtl.newTIProcSig([["aPosition",$mod.$rtti["TJSPosition"]]]), methodkind: 0});
  $mod.$rtti.$ProcVar("TJSGeoLocationErrorCallback",{procsig: rtl.newTIProcSig([["aValue",$mod.$rtti["TJSPositionError"]]])});
  $mod.$rtti.$MethodVar("TJSGeoLocationErrorEvent",{procsig: rtl.newTIProcSig([["aValue",$mod.$rtti["TJSPositionError"]]]), methodkind: 0});
  $mod.$rtti.$ExtClass("TJSGeoLocation",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "GeoLocation"});
  $mod.$rtti.$ExtClass("TJSMediaStreamTrack",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "MediaStreamTrack"});
  $mod.$rtti.$RefToProcVar("TJSMediaStreamTrackProc",{procsig: rtl.newTIProcSig([["aMediaStreamTrack",$mod.$rtti["TJSMediaStreamTrack"]]])});
  $mod.$rtti.$ExtClass("TJSMediaStreamTracks",{ancestor: pas.JS.$rtti["TJSArray"], jsclass: "Array"});
  $mod.$rtti.$ExtClass("TJSMediaConstraints",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSMediaStream",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "MediaStream"});
  $mod.$rtti.$ExtClass("TJSMediaDeviceInfo",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "MediaDeviceInfo"});
  $mod.$rtti.$RefToProcVar("TJSMediaDeviceInfoProc",{procsig: rtl.newTIProcSig([["aMediaStreamTrack",$mod.$rtti["TJSMediaStreamTrack"]]])});
  $mod.$rtti.$ExtClass("TJSMediaDeviceInfoArray",{ancestor: pas.JS.$rtti["TJSArray"], jsclass: "Array"});
  $mod.$rtti.$ExtClass("TJSMediaTrackSupportedConstraints",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "MediaTrackSupportedConstraints"});
  $mod.$rtti.$RefToProcVar("TJSMediaTrackSupportedConstraintsProc",{procsig: rtl.newTIProcSig([["aConstraints",$mod.$rtti["TJSMediaTrackSupportedConstraints"]]])});
  $mod.$rtti.$ExtClass("TJSMediaTrackSupportedConstraintsArray",{ancestor: pas.JS.$rtti["TJSArray"], jsclass: "Array"});
  $mod.$rtti.$ExtClass("TJSMediaDevices",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "MediaDevices"});
  $mod.$rtti.$ExtClass("TJSSharedWorker",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "SharedWorker"});
  rtl.recNewT($mod,"TJSServiceWorkerContainerOptions",function () {
    this.scope = "";
    this.$eq = function (b) {
      return this.scope === b.scope;
    };
    this.$assign = function (s) {
      this.scope = s.scope;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSServiceWorkerContainerOptions",{});
    $r.addField("scope",rtl.string);
  });
  $mod.$rtti.$ExtClass("TJSServiceWorkerContainer",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "ServiceWorkerContainer"});
  $mod.$rtti.$ExtClass("TJSClipboardItemOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSClipBoardItem",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "ClipboardItem"});
  $mod.$rtti.$ExtClass("TJSClipBoard",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "Clipboard"});
  $mod.$rtti.$ExtClass("TJSNavigator",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Navigator"});
  $mod.$rtti.$ExtClass("TJSTouch",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Touch"});
  $mod.$rtti.$ExtClass("TJSTouchList",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "TouchList"});
  $mod.$rtti.$ExtClass("TJSScreen",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Screen"});
  $mod.$rtti.$ExtClass("TJSMediaQueryList",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "MediaQueryList"});
  $mod.$rtti.$RefToProcVar("TFrameRequestCallback",{procsig: rtl.newTIProcSig([["aTime",rtl.double]])});
  $mod.$rtti.$ExtClass("TJSPostMessageOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  rtl.createClass($mod,"TJSIdleCallbackOptions",pas.System.TObject,function () {
    this.$init = function () {
      pas.System.TObject.$init.call(this);
      this.timeout = 0;
    };
  });
  $mod.$rtti.$ExtClass("TJSIdleDeadline",{jsclass: "IdleDeadline"});
  $mod.$rtti.$DynArray("TJSWindowArray",{eltype: $mod.$rtti["TJSWindow"]});
  $mod.$rtti.$RefToProcVar("TIdleCallbackProc",{procsig: rtl.newTIProcSig([["idleDeadline",$mod.$rtti["TJSIdleDeadline"]]])});
  $mod.$rtti.$ExtClass("TJSWindow",{ancestor: pas.weborworker.$rtti["TWindowOrWorkerGlobalScope"], jsclass: "Window"});
  $mod.$rtti.$ExtClass("TJSCSSStyleDeclaration",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "CSSStyleDeclaration"});
  $mod.$rtti.$ExtClass("TJSScrollIntoViewOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSDatasetMap",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSHTMLElement",{ancestor: $mod.$rtti["TJSElement"], jsclass: "HTMLElement"});
  $mod.$rtti.$DynArray("TJSHTMLElementArray",{eltype: $mod.$rtti["TJSHTMLElement"]});
  $mod.$rtti.$ExtClass("TJSHTMLDivElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLDivElement"});
  $mod.$rtti.$ExtClass("TJSHTMLFormControlsCollection",{ancestor: $mod.$rtti["TJSHTMLCollection"], jsclass: "HTMLFormControlsCollection"});
  $mod.$rtti.$ExtClass("TJSHTMLFormElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLFormElement"});
  $mod.$rtti.$ExtClass("TJSValidityState",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "ValidityState"});
  $mod.$rtti.$ExtClass("TJSHTMLFile",{ancestor: pas.weborworker.$rtti["TJSBlob"], jsclass: "File"});
  $mod.$rtti.$ExtClass("TJSHTMLFileList",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "FileList"});
  $mod.$rtti.$ExtClass("TJSHTMLInputElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLInputElement"});
  $mod.$rtti.$ExtClass("TJSDOMSettableTokenList",{ancestor: $mod.$rtti["TJSDOMTokenList"], jsclass: "DOMSettableTokenList"});
  $mod.$rtti.$ExtClass("TJSHTMLOutputElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLOutputElement"});
  $mod.$rtti.$ExtClass("TJSHTMLImageElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "Image"});
  $mod.$rtti.$ExtClass("TJSHTMLLinkElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLLinkElement"});
  $mod.$rtti.$ExtClass("TJSHTMLAnchorElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLAnchorElement"});
  $mod.$rtti.$ExtClass("TJSHTMLMenuElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLMenuElement"});
  $mod.$rtti.$ExtClass("TJSHTMLButtonElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLButtonElement"});
  $mod.$rtti.$ExtClass("TJSHTMLLabelElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLLabelElement"});
  $mod.$rtti.$ExtClass("TJSHTMLTextAreaElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLTextAreaElement"});
  $mod.$rtti.$ExtClass("TJSHTMLEmbedElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLEmbedElement"});
  $mod.$rtti.$ExtClass("TJSHTMLOptionElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "Option"});
  $mod.$rtti.$ExtClass("TJSHTMLOptGroupElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLOptGroupElement"});
  $mod.$rtti.$ExtClass("TJSHTMLOptionsCollection",{ancestor: $mod.$rtti["TJSHTMLCollection"], jsclass: "HTMLOptionsCollection"});
  $mod.$rtti.$ExtClass("TJSHTMLSelectElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLSelectElement"});
  $mod.$rtti.$ExtClass("TJSHTMLTableSectionElement");
  $mod.$rtti.$ExtClass("TJSHTMLTableRowElement");
  $mod.$rtti.$ExtClass("TJSHTMLTableElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLTableElement"});
  $mod.$rtti.$ExtClass("TJSHTMLTableSectionElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLTableSectionElement"});
  $mod.$rtti.$ExtClass("TJSHTMLTableCellElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLTableCellElement"});
  $mod.$rtti.$ExtClass("TJSHTMLTableRowElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLTableRowElement"});
  $mod.$rtti.$ExtClass("TJSHTMLTableDataCellElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLTableDataCellElement"});
  $mod.$rtti.$ExtClass("TJSCanvasRenderingContext2D");
  $mod.$rtti.$RefToProcVar("THTMLCanvasToBlobCallback",{procsig: rtl.newTIProcSig([["aBlob",pas.weborworker.$rtti["TJSBlob"]]],rtl.boolean,8)});
  $mod.$rtti.$ExtClass("TJSHTMLCanvasElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLCanvasElement"});
  $mod.$rtti.$ExtClass("TJSHTMLProgressElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLProgressElement"});
  $mod.$rtti.$ExtClass("TJSCanvasRenderingContext2D",{ancestor: pas.weborworker.$rtti["TJSBaseCanvasRenderingContext2D"], jsclass: "CanvasRenderingContext2D"});
  $mod.$rtti.$ExtClass("TJSHTMLIFrameElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLIFrameElement"});
  $mod.$rtti.$ExtClass("TJSHTMLScriptElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLScriptElement"});
  $mod.$rtti.$ExtClass("TJSXMLHttpRequestEventTarget",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "XMLHttpRequestEventTarget"});
  $mod.$rtti.$ExtClass("TJSXMLHttpRequestUpload",{ancestor: $mod.$rtti["TJSXMLHttpRequestEventTarget"], jsclass: "XMLHttpRequestUpload"});
  $mod.$rtti.$RefToProcVar("TJSOnReadyStateChangeHandler",{procsig: rtl.newTIProcSig(null,8)});
  $mod.$rtti.$ExtClass("TJSXMLHttpRequest",{ancestor: $mod.$rtti["TJSXMLHttpRequestEventTarget"], jsclass: "XMLHttpRequest"});
  $mod.$rtti.$ExtClass("TJSUIEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "UIEvent"});
  $mod.$rtti.$ExtClass("TJSMouseEvent",{ancestor: $mod.$rtti["TJSUIEvent"], jsclass: "MouseEvent"});
  rtl.recNewT($mod,"TJSWheelEventInit",function () {
    this.deltaX = 0.0;
    this.deltaY = 0.0;
    this.deltaZ = 0.0;
    this.deltaMode = 0;
    this.$eq = function (b) {
      return (this.deltaX === b.deltaX) && (this.deltaY === b.deltaY) && (this.deltaZ === b.deltaZ) && (this.deltaMode === b.deltaMode);
    };
    this.$assign = function (s) {
      this.deltaX = s.deltaX;
      this.deltaY = s.deltaY;
      this.deltaZ = s.deltaZ;
      this.deltaMode = s.deltaMode;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSWheelEventInit",{});
    $r.addField("deltaX",rtl.double);
    $r.addField("deltaY",rtl.double);
    $r.addField("deltaZ",rtl.double);
    $r.addField("deltaMode",rtl.nativeint);
  });
  $mod.$rtti.$ExtClass("TJSWheelEvent",{ancestor: $mod.$rtti["TJSMouseEvent"], jsclass: "WheelEvent"});
  $mod.$rtti.$ExtClass("TJSPointerEvent",{ancestor: $mod.$rtti["TJSMouseEvent"], jsclass: "PointerEvent"});
  $mod.$rtti.$ExtClass("TJSTouchEvent",{ancestor: $mod.$rtti["TJSUIEvent"], jsclass: "TouchEvent"});
  rtl.createClass($mod,"TJSKeyNames",pas.System.TObject,function () {
    this.Alt = "Alt";
    this.AltGraph = "AltGraph";
    this.CapsLock = "CapsLock";
    this.Control = "Control";
    this.Fn = "Fn";
    this.FnLock = "FnLock";
    this.Hyper = "Hyper";
    this.Meta = "Meta";
    this.NumLock = "NumLock";
    this.ScrollLock = "ScrollLock";
    this.Shift = "Shift";
    this.Super = "Super";
    this.Symbol = "Symbol";
    this.SymbolLock = "SymbolLock";
    this.Enter = "Enter";
    this.Tab = "Tab";
    this.Space = "Space";
    this.ArrowDown = "ArrowDown";
    this.ArrowLeft = "ArrowLeft";
    this.ArrowRight = "ArrowRight";
    this.ArrowUp = "ArrowUp";
    this._End = "End";
    this.Home = "Home";
    this.PageDown = "PageDown";
    this.PageUp = "PageUp";
    this.BackSpace = "Backspace";
    this.Clear = "Clear";
    this.Copy = "Copy";
    this.CrSel = "CrSel";
    this.Cut = "Cut";
    this.Delete = "Delete";
    this.EraseEof = "EraseEof";
    this.ExSel = "ExSel";
    this.Insert = "Insert";
    this.Paste = "Paste";
    this.Redo = "Redo";
    this.Undo = "Undo";
    this.Accept = "Accept";
    this.Again = "Again";
    this.Attn = "Attn";
    this.Cancel = "Cancel";
    this.ContextMenu = "Contextmenu";
    this.Escape = "Escape";
    this.Execute = "Execute";
    this.Find = "Find";
    this.Finish = "Finish";
    this.Help = "Help";
    this.Pause = "Pause";
    this.Play = "Play";
    this.Props = "Props";
    this.Select = "Select";
    this.ZoomIn = "ZoomIn";
    this.ZoomOut = "ZoomOut";
    this.BrightnessDown = "BrightnessDown";
    this.BrightnessUp = "BrightnessUp";
    this.Eject = "Eject";
    this.LogOff = "LogOff";
    this.Power = "Power";
    this.PowerOff = "PowerOff";
    this.PrintScreen = "PrintScreen";
    this.Hibernate = "Hibernate";
    this.Standby = "Standby";
    this.WakeUp = "WakeUp";
    this.AllCandidates = "AllCandidates";
    this.Alphanumeric = "Alphanumeric";
    this.CodeInput = "CodeInput";
    this.Compose = "Compose";
    this.Convert = "Convert";
    this.Dead = "Dead";
    this.FinalMode = "FinalMode";
    this.GroupFirst = "GroupFirst";
    this.GroupLast = "GroupLast";
    this.GroupNext = "GroupNext";
    this.GroupPrevious = "GroupPrevious";
    this.ModelChange = "ModelChange";
    this.NextCandidate = "NextCandidate";
    this.NonConvert = "NonConvert";
    this.PreviousCandidate = "PreviousCandidate";
    this.Process = "Process";
    this.SingleCandidate = "SingleCandidate";
    this.HangulMode = "HangulMode";
    this.HanjaMode = "HanjaMode";
    this.JunjaMode = "JunjaMode";
    this.Eisu = "Eisu";
    this.Hankaku = "Hankaku";
    this.Hiranga = "Hiranga";
    this.HirangaKatakana = "HirangaKatakana";
    this.KanaMode = "KanaMode";
    this.Katakana = "Katakana";
    this.Romaji = "Romaji";
    this.Zenkaku = "Zenkaku";
    this.ZenkakuHanaku = "ZenkakuHanaku";
    this.F1 = "F1";
    this.F2 = "F2";
    this.F3 = "F3";
    this.F4 = "F4";
    this.F5 = "F5";
    this.F6 = "F6";
    this.F7 = "F7";
    this.F8 = "F8";
    this.F9 = "F9";
    this.F10 = "F10";
    this.F11 = "F11";
    this.F12 = "F12";
    this.F13 = "F13";
    this.F14 = "F14";
    this.F15 = "F15";
    this.F16 = "F16";
    this.F17 = "F17";
    this.F18 = "F18";
    this.F19 = "F19";
    this.F20 = "F20";
    this.Soft1 = "Soft1";
    this.Soft2 = "Soft2";
    this.Soft3 = "Soft3";
    this.Soft4 = "Soft4";
    this.Decimal = "Decimal";
    this.Key11 = "Key11";
    this.Key12 = "Key12";
    this.Multiply = "Multiply";
    this.Add = "Add";
    this.NumClear = "Clear";
    this.Divide = "Divide";
    this.Subtract = "Subtract";
    this.Separator = "Separator";
    this.AppSwitch = "AppSwitch";
    this.Call = "Call";
    this.Camera = "Camera";
    this.CameraFocus = "CameraFocus";
    this.EndCall = "EndCall";
    this.GoBack = "GoBack";
    this.GoHome = "GoHome";
    this.HeadsetHook = "HeadsetHook";
    this.LastNumberRedial = "LastNumberRedial";
    this.Notification = "Notification";
    this.MannerMode = "MannerMode";
    this.VoiceDial = "VoiceDial";
  });
  $mod.$rtti.$ExtClass("TJSKeyboardEvent",{ancestor: $mod.$rtti["TJSUIEvent"], jsclass: "KeyboardEvent"});
  $mod.$rtti.$ExtClass("TJSInputEvent",{ancestor: $mod.$rtti["TJSUIEvent"], jsclass: "InputEvent"});
  $mod.$rtti.$ExtClass("TJSMutationObserver");
  rtl.recNewT($mod,"TJSMutationRecord",function () {
    this.type_ = "";
    this.target = null;
    this.addedNodes = null;
    this.removedNodes = null;
    this.previousSibling = null;
    this.nextSibling = null;
    this.attributeName = "";
    this.attributeNamespace = "";
    this.oldValue = "";
    this.$eq = function (b) {
      return (this.type_ === b.type_) && (this.target === b.target) && (this.addedNodes === b.addedNodes) && (this.removedNodes === b.removedNodes) && (this.previousSibling === b.previousSibling) && (this.nextSibling === b.nextSibling) && (this.attributeName === b.attributeName) && (this.attributeNamespace === b.attributeNamespace) && (this.oldValue === b.oldValue);
    };
    this.$assign = function (s) {
      this.type_ = s.type_;
      this.target = s.target;
      this.addedNodes = s.addedNodes;
      this.removedNodes = s.removedNodes;
      this.previousSibling = s.previousSibling;
      this.nextSibling = s.nextSibling;
      this.attributeName = s.attributeName;
      this.attributeNamespace = s.attributeNamespace;
      this.oldValue = s.oldValue;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSMutationRecord",{});
    $r.addField("type_",rtl.string);
    $r.addField("target",$mod.$rtti["TJSNode"]);
    $r.addField("addedNodes",$mod.$rtti["TJSNodeList"]);
    $r.addField("removedNodes",$mod.$rtti["TJSNodeList"]);
    $r.addField("previousSibling",$mod.$rtti["TJSNode"]);
    $r.addField("nextSibling",$mod.$rtti["TJSNode"]);
    $r.addField("attributeName",rtl.string);
    $r.addField("attributeNamespace",rtl.string);
    $r.addField("oldValue",rtl.string);
  });
  $mod.$rtti.$DynArray("TJSMutationRecordArray",{eltype: $mod.$rtti["TJSMutationRecord"]});
  $mod.$rtti.$RefToProcVar("TJSMutationCallback",{procsig: rtl.newTIProcSig([["mutations",$mod.$rtti["TJSMutationRecordArray"]],["observer",$mod.$rtti["TJSMutationObserver"]]],8)});
  rtl.recNewT($mod,"TJSMutationObserverInit",function () {
    this.attributes = false;
    this.attributeOldValue = false;
    this.characterData = false;
    this.characterDataOldValue = false;
    this.childList = false;
    this.subTree = false;
    this.attributeFilter = null;
    this.$eq = function (b) {
      return (this.attributes === b.attributes) && (this.attributeOldValue === b.attributeOldValue) && (this.characterData === b.characterData) && (this.characterDataOldValue === b.characterDataOldValue) && (this.childList === b.childList) && (this.subTree === b.subTree) && (this.attributeFilter === b.attributeFilter);
    };
    this.$assign = function (s) {
      this.attributes = s.attributes;
      this.attributeOldValue = s.attributeOldValue;
      this.characterData = s.characterData;
      this.characterDataOldValue = s.characterDataOldValue;
      this.childList = s.childList;
      this.subTree = s.subTree;
      this.attributeFilter = s.attributeFilter;
      return this;
    };
    var $r = $mod.$rtti.$Record("TJSMutationObserverInit",{});
    $r.addField("attributes",rtl.boolean);
    $r.addField("attributeOldValue",rtl.boolean);
    $r.addField("characterData",rtl.boolean);
    $r.addField("characterDataOldValue",rtl.boolean);
    $r.addField("childList",rtl.boolean);
    $r.addField("subTree",rtl.boolean);
    $r.addField("attributeFilter",pas.JS.$rtti["TJSArray"]);
  });
  $mod.$rtti.$ExtClass("TJSMutationObserver",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "MutationObserver"});
  $mod.$rtti.$ExtClass("TJSWebsocketCloseEvent",{ancestor: pas.weborworker.$rtti["TJSEvent"], jsclass: "CloseEvent"});
  $mod.$rtti.$ExtClass("TJSWebSocket",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "WebSocket"});
  $mod.$rtti.$ExtClass("TJSHTMLAudioTrack",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "AudioTrack"});
  $mod.$rtti.$ExtClass("TJSHTMLAudioTrackList",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "AudioTrackList"});
  $mod.$rtti.$ExtClass("TJSHTMLVideoTrack",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "VideoTrack"});
  $mod.$rtti.$ExtClass("TJSHTMLVideoTrackList",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "VideoTrackList"});
  $mod.$rtti.$ExtClass("TJSHTMLTextTrack",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "TextTrack"});
  $mod.$rtti.$ExtClass("TJSHTMLTextTrackList",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "TextTrackList"});
  $mod.$rtti.$ExtClass("TJSMEdiaError",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "MediaError"});
  $mod.$rtti.$ExtClass("TJSHTMLMediaController",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "MediaController"});
  $mod.$rtti.$ExtClass("TJSHTMLMediaElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLMediaElement"});
  $mod.$rtti.$ExtClass("TJSHTMLAudioElement",{ancestor: $mod.$rtti["TJSHTMLMediaElement"], jsclass: "HTMLAudioElement"});
  $mod.$rtti.$ExtClass("TJSVideoFrameMetaData",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSPictureInPictureWindow",{ancestor: pas.weborworker.$rtti["TJSEventTarget"], jsclass: "PictureInPictureWindow"});
  $mod.$rtti.$ExtClass("TJSVideoPlaybackQuality",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "VideoPlaybackQuality"});
  $mod.$rtti.$RefToProcVar("TRequestVideoFrameCallback",{procsig: rtl.newTIProcSig([["aNow",rtl.double],["metaData",$mod.$rtti["TJSVideoFrameMetaData"]]])});
  $mod.$rtti.$ExtClass("TJSHTMLVideoElement",{ancestor: $mod.$rtti["TJSHTMLMediaElement"], jsclass: "HTMLVideoElement"});
  $mod.$rtti.$ExtClass("TJSHTMLStyleElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLStyleElement"});
  $mod.$rtti.$DynArray("TJSFormDataEntryValueArray",{eltype: rtl.string});
  $mod.$rtti.$ExtClass("TJSFormData",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "FormData"});
  $mod.$rtti.$ExtClass("TJSHTMLTemplateElement",{ancestor: $mod.$rtti["TJSHTMLElement"], jsclass: "HTMLTemplateElement"});
  $mod.$rtti.$ExtClass("TJSHTMLOrXMLDocument",{ancestor: $mod.$rtti["TJSDocument"], jsclass: "Document"});
  $mod.$rtti.$ExtClass("TJSHTMLDocument",{ancestor: $mod.$rtti["TJSHTMLOrXMLDocument"], jsclass: "HTMLDocument"});
  $mod.$rtti.$ExtClass("TJSXMLDocument",{ancestor: $mod.$rtti["TJSHTMLOrXMLDocument"], jsclass: "HTMLDocument"});
  $mod.$rtti.$ExtClass("TDOMParser",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "DOMParser"});
  $mod.$rtti.$ExtClass("TJSShowOpenFilePickerTypeOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSShowOpenFilePickerOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSShowSaveFilePickerOptionsAccept",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSShowSaveFilePickerOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSXSLTProcessor",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "XSLTProcessor"});
  $mod.$rtti.$ExtClass("TJSXMLSerializer",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "XMLSerializer"});
  $mod.$rtti.$ExtClass("TJSSizeElement",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$DynArray("TJSSizeElementArray",{eltype: $mod.$rtti["TJSSizeElement"]});
  $mod.$rtti.$ExtClass("TJSHTMLResizeObserverEntry",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$DynArray("TJSHTMLResizeObserverEntryArray",{eltype: $mod.$rtti["TJSHTMLResizeObserverEntry"]});
  $mod.$rtti.$RefToProcVar("TJSHTMLResizeObserverCallback",{procsig: rtl.newTIProcSig([["Entries",$mod.$rtti["TJSHTMLResizeObserverEntryArray"]],["aObserver",$mod.$rtti["TJSHTMLResizeObserver"]]])});
  $mod.$rtti.$ExtClass("TJSHTMLResizeObserverOptions",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSHTMLResizeObserver",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "ResizeObserver"});
  $mod.$rtti.$ExtClass("TJSAnimationTimeline",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "AnimationTimeline"});
  $mod.$rtti.$ExtClass("TJSAnimationTiming",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Object"});
  $mod.$rtti.$ExtClass("TJSAnimationEffect",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "AnimationEffect"});
  $mod.$rtti.$ExtClass("TJSAnimation",{ancestor: pas.JS.$rtti["TJSObject"], jsclass: "Animation"});
  this.HasServiceWorker = function () {
    var Result = false;
    if (window.navigator.serviceWorker) {
      return true}
     else return false;
    return Result;
  };
});
